before_install:
  - git submodule update --init --recursive
language: node_js
node_js:
  - "14"
before_script:
  - npm install
script: npm run build
deploy:
  local-dir: dist/collegues-front
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
notifications:
  email: false
